/**
 * Define the random names 
 */
var avatars = [
  "./img/avatar/001.png",
  "./img/avatar/002.png",
  "./img/avatar/003.png",
  "./img/avatar/004.png",
  "./img/avatar/005.png",
  "./img/avatar/006.png",
  "./img/avatar/007.png",
  "./img/avatar/008.png",
  "./img/avatar/009.png",
  "./img/avatar/010.png",
  "./img/avatar/011.png",
  "./img/avatar/012.png",
  "./img/avatar/013.png",
  "./img/avatar/014.png",
  "./img/avatar/015.png",
  "./img/avatar/016.png",
  "./img/avatar/017.png",
  "./img/avatar/018.png",
  "./img/avatar/019.png",
  "./img/avatar/020.png"
]
var names = [
    'Christopher Robinson',
    'Alexander Lewis',
    'Allen Maxwell',
    'Michael Walls',
    'Tanner Allen',
    'Keith Arellano',
    'John Farley',
    'Michael Hurst',
    'Timothy Gray',
    'David Carlson',
    'Christopher Curtis',
    'Travis Glover',
    'Christopher Martin',
    'Richard Dunlap',
    'Daniel Parker',
    'Justin Horton',
    'Ronald Harris',
    'Timothy Parker',
    'Guy Smith',
    'Matthew Stevens',
    'George Washington',
    'Timothy Kelly',
    'Jimmy Martinez',
    'Christopher Collier',
    'Jimmy Crawford',
    'Jeffrey Mccoy',
    'Jack Miller',
    'Richard Williams',
    'Eric Clark',
    'Andrew Foley',
    'Levi Rhodes',
    'Marco Jones',
    'Brian Torres',
    'Robert Lynch',
    'Mark Murillo',
    'Joseph Spencer',
    'Roberto Williams',
    'Antonio Nelson',
    'John Ramirez',
    'James Robinson',
    'Samuel Chambers',
    'William Lawrence',
    'Tim Howell',
    'Joseph Carter',
    'Bradley Brock',
    'Roger Smith',
    'Charles Turner',
    'Gregory Obrien',
    'Jacob Mayer',
    'Travis Christian',
    'Matthew Watson',
    'Barry Adams',
    'Caleb Daniels',
    'William Hernandez',
    'Steven Gomez',
    'Nicholas Lewis',
    'Brian Lucas',
    'Eric Stafford',
    'David Dawson',
    'Michael Newton',
    'Jordan Lloyd',
    'Brian Kelley',
    'Chad Howard',
    'Aaron Ochoa',
    'Christopher Knight',
    'Alexander Cox',
    'Nicholas Matthews',
    'Joseph Miller',
    'Devin Duncan',
    'Michael Luna',
    'Brian Pearson',
    'Joseph Johnson',
    'Richard Castaneda',
    'Brent Evans',
    'Robert Brown',
    'Michael Hughes',
    'Andrew David',
    'Jeremy Vazquez',
    'Karl Jackson',
    'William Garza',
    'Micheal Brown',
    'Michael Avery',
    'David Moore',
    'Thomas Martin',
    'Danny Fitzgerald',
    'Darin Zamora',
    'Jorge Larsen',
    'Travis Ward',
    'Paul Adkins',
    'Eric Ruiz',
    'Dr. Steven Martinez',
    'James Peterson',
    'Douglas Johnson',
    'Joseph Walker',
    'Terrance Bishop',
    'Jason Watkins',
    'Richard Bruce',
    'Luis Knox',
    'Justin Foster',
    'Alexis Hayden',
    'Melissa Schmidt',
    'Tara Hayes',
    'Melissa Woodward',
    'Vanessa Lopez',
    'Valerie Peterson',
    'Jamie Lewis',
    'Patricia Watson',
    'Jennifer Gonzales',
    'Megan Sellers',
    'Belinda Parker',
    'Amber Sanders',
    'Makayla Carrillo',
    'Susan Wheeler',
    'Cheryl Edwards',
    'Jennifer Anderson',
    'Amy Brown',
    'Lauren Gilbert',
    'Debra Carlson MD',
    'Jaime Dixon',
    'Michelle Johnson',
    'Natalie Key',
    'Marilyn Bradley',
    'Jennifer Estes',
    'Melissa Pruitt',
    'Melissa Porter',
    'Nicole Powers',
    'Leslie Caldwell',
    'Julie Howell',
    'Sarah Hampton DVM',
    'Elizabeth Schmitt',
    'Cathy Sosa',
    'Sabrina Sawyer',
    'Patricia Nash',
    'Yolanda Sandoval',
    'Kimberly Williams',
    'Tonya Sawyer DDS',
    'Jamie Rowland',
    'Holly Rogers',
    'Cynthia Kelly',
    'Lisa Sloan',
    'Heather Ellis',
    'Mary English',
    'Ashley Nelson',
    'Angela Jensen',
    'Jennifer Wu',
    'Janet Rodriguez',
    'Morgan Manning',
    'Erin Hodge',
    'Mary Duffy',
    'Tracy Bass',
    'Michelle Wolfe',
    'Michele White',
    'Amanda Garcia',
    'Rachel White',
    'Amy Cruz',
    'Sharon Meza',
    'Veronica Moore',
    'Kristin Williams',
    'Karen Lee',
    'Linda Henderson',
    'Janice Wilson',
    'Jennifer Davis',
    'Erica Mendez',
    'Ruth Crawford',
    'Ashley Torres',
    'Julie Aguilar',
    'Ann Santana',
    'Erin Rodriguez',
    'Latoya Jones',
    'Shelia Cruz',
    'Melissa Bullock',
    'Megan Hood',
    'Megan Miller',
    'Brittany Dawson',
    'Katherine Morrison',
    'Christine Anderson',
    'Victoria Wilson',
    'Jessica Vargas',
    'Dawn Tran',
    'Deanna Lam',
    'Debra Mclean',
    'Becky Baker',
    'Linda Harris',
    'Sarah Aguilar',
    'Samantha Brown',
    'Janet Vazquez',
    'Theresa Cox',
    'Andrea Banks',
    'Briana Russell',
    'Amanda Chang',
    'Tiffany Howell',
    'Mary Davis',
    'Jill Gomez',
    'Cynthia Bray MD',
    'Kimberly Ponce',
    'Linda Clay',
    'Susan Alvarez',
    'Grace Steele'
  ]

